In [4]:
x = list(range(1,11,1))
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
import numpy as np

y = np.random.random((2,3,2))
y

array([[[0.31092148, 0.78913999],
        [0.39765027, 0.66885504],
        [0.98742028, 0.98805142]],

       [[0.49693287, 0.70318053],
        [0.59658784, 0.48647587],
        [0.37969559, 0.54586683]]])

In [25]:
y[0,0]

array([0.31092148, 0.78913999])

In [47]:
def function (array1, array2):
    return array(sum(array1 + array2))
    

In [49]:
print(function(y[0,0], y[1,0]))

[0.80785435 1.49232052]


In [39]:
y[0,0] + y[1,0]

array([0.80785435, 1.49232052])

In [60]:
challenge_list = [1,2,3,4,5]
new_list = []
challenge_list
for i in challenge_list:
#     challenge_list.index(i)
    new_list.append(i*challenge_list.index(i))
    new_list.append(i+challenge_list.index(i))
print(new_list)

[0, 1, 2, 3, 6, 5, 12, 7, 20, 9]
