# Day 03

### Practice:

In [2]:
#Create a list that contains the names of your classmates
classmates = ["Christiaan", "Princess", "Thoa", "Maia", "Gary", "Patrick"]
# Print out the number of elements in the list 
print(len(classmates))
#Print out the last person in the list
print(classmates[-1])
# Print out the 3rd-5th persons in the list
print(classmates[2:5])

6
Patrick
['Thoa', 'Maia', 'Gary']


In [3]:
# Y’all have a new classmate. Add Bob to the list of classmates. 
classmates.append("Bob")
print(classmates)
# Actually, Bob is a software engineering student. Remove his name from the list 
classmates.pop()
print(classmates)

['Christiaan', 'Princess', 'Thoa', 'Maia', 'Gary', 'Patrick', 'Bob']
['Christiaan', 'Princess', 'Thoa', 'Maia', 'Gary', 'Patrick']


In [4]:
# Challenge: Write a for loop to print out each person in the list 
for person in classmates:
    print(person)

Christiaan
Princess
Thoa
Maia
Gary
Patrick


### **Question:**

Why might we want some data types to mutable and others to be immutable?

***Add response here:***

# Day 05

### Practice:

In [61]:
# Create a list with elements ranging from 1 to 10
import numpy as np
range_list = list(range(1,11))
print(range_list)
# Create an array with the shape (2, 3)
test = [[2,3, 4], [5,4, 4]]
test_array = np.array(test)
print(test_array)
# Print the first row of the array
test_array[0]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[2 3 4]
 [5 4 4]]


array([2, 3, 4])

In [68]:
# Challenge: Create a function that adds together two arrays
def add_list(array1, array2):
    return array1 + array2

In [70]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
add_list(array1,array2)

array([5, 7, 9])

### **Question:**

What are some differences between a list and a numpy array?

***Add response here:***
    
