# Day 05

### Practice:

In [61]:
# Create a list with elements ranging from 1 to 10
import numpy as np
range_list = list(range(1,11))
print(range_list)
# Create an array with the shape (2, 3)
test = [[2,3, 4], [5,4, 4]]
test_array = np.array(test)
print(test_array)
# Print the first row of the array
test_array[0]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[2 3 4]
 [5 4 4]]


array([2, 3, 4])

In [68]:
# Challenge: Create a function that adds together two arrays
def add_list(array1, array2):
    return array1 + array2

In [70]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
add_list(array1,array2)

array([5, 7, 9])

### **Question:**

What are some differences between a list and a numpy array?

***Add response here:***
    
